morris_butler/urls.py
from django.urls import path, include
from ckeditor_uploader import views
import calendars.urls
import notes.urls
import todo.urls
import userprofile.urls
import admin.urls
import notes.views
import todo.views
import calendars.views
from main.views import *
from django.conf.urls.static import static
from morris_butler import settings
from django.contrib.auth.decorators import login_required

from userprofile.views import confirm_mail

urlpatterns = [
    path('admin/', include(admin.urls)),
    path('', index, name='index'),
    path('notes/', include(notes.urls)),
    path('calendar', calendars.views.index, name='calendar.index'),
    path('calendar/', include(calendars.urls)),
    path('todo/', include(todo.urls)),
    path('userprofile/', include(userprofile.urls)),
    path('sign_in/', sign_in_ajax, name='sign_in'),
    path('sign_out/', sign_out_view, name='sign_out'),
    path('sign_up/', sign_up_ajax, name='sign_up'),
    path('activate/<str:key>', activate_key, name='activate_key'),
    path('confirm_mail/<str:key>', confirm_mail, name='confirm_mail'),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from todo.views import *

urlpatterns = [
    path('', index, name='todo.index'),
    path('save', save_todo, name='todo.save'),
    path('get_note_data', get_todo_data, name='todo.get_todo_data'),
    path('delete', delete_todo, name='todo.delete'),
    path('sort', sort, name='todo.sort'),
    path('get_folder', get_folder, name='todo.get_folder'),
    path('search', search, name='todo.search')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from morris_butler.settings import TIME_ZONE


class Language(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lang = models.CharField(max_length=3, default="ru")


class Timezone(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timezone = models.CharField(max_length=50, default=TIME_ZONE)


class ConfirmKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    key = models.CharField(max_length=256)
    expiration_date = models.DateField(default="2018-01-01")


class ConfirmMailKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    key = models.CharField(max_length=256)
    email = models.CharField(max_length=150)


def modification_of_user_data(user, name=None, surname=None, username=None):
    """!
            @brief Function that saves modified user data if it is valid
    """
    if name is not None:
        user.first_name = name
    if surname is not None:
        user.last_name = surname
    user.save()
    if username is not None:
        if User.objects.filter(username=username).count() == 0:
            user.username = username
            user.save()
        else:
            return False
    return True

main/forms.py
from django import forms


class SignInForm(forms.Form):
    """!
        @brief Form that handles user's data while signing in process
    """
    username_sign_in = forms.CharField(label='Email or username', max_length=200,
                                       widget=forms.TextInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'Enter your e-mail or username'}))
    password = forms.CharField(label='Password', max_length=200,
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Enter your password'}))


class SignUpForm(forms.Form):
    """!
        @brief Form that handles user's data while signing up process
    """
    email = forms.EmailField(label='E-mail', max_length=200,
                             widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'placeholder': 'Enter your e-mail'}))
    username = forms.CharField(label='Username', max_length=200,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Enter your username'}))
    name = forms.CharField(label='Name', max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'Enter your name'}))
    surname = forms.CharField(label='Surname', max_length=200,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Enter your surname'}))
    password1 = forms.CharField(label='Password', max_length=200,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Enter your password'}))
    password2 = forms.CharField(label='Password again', max_length=200,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Enter your password again'}))
    language = forms.CharField(max_length=50, widget=forms.HiddenInput)
    timezone = forms.CharField(max_length=50, widget=forms.HiddenInput)

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from main.forms import *
from main.models import *
import json
import hashlib
import binascii
from django.utils import timezone
from django.core.mail import EmailMultiAlternatives
from morris_butler.settings import SECRET_KEY, EMAIL_HOST_USER, SUPPORTED_LANGUAGES,\
    SUPPORTED_LANGUAGES_CODES, SUPPORTED_TIMEZONES
from calendars.forms import AddEventForm
from notes.forms import *
from notes.models import *
from todo.models import *
from calendars.models import *
from django.contrib.auth.models import User
from userprofile.forms import RecoverPasswordUserData
from todo.forms import SaveTodoForm, EditTodoForm
from localisation import rus, eng
import pytz


def index(request):
    """!
            @brief Function that renders home page if user is authenticated and index page if not
    """
    if request.method == "GET":
        context = {
            'title': 'Index page'
        }
        if not request.user.is_authenticated:
            sign_in_form = SignInForm()
            context['sign_in_form'] = sign_in_form
            sign_up_form = SignUpForm()
            context['sign_up_form'] = sign_up_form
            recover_password_user_data_form = RecoverPasswordUserData()
            context['recover_password_form'] = recover_password_user_data_form
            context['timezones'] = SUPPORTED_TIMEZONES
            context['supported_languages'] = SUPPORTED_LANGUAGES
            return render(request, "main/index.html", context)
        else:
            context['lang'], context['language'] = get_language(request)
            events = Event.objects.filter(user=request.user)
            notes = Notes.objects.filter(user=request.user)
            todos = Todos.objects.filter(user=request.user)
            date = timezone.now()
            today_event = events.filter(date=date.date()).first()
            if today_event:
                context['today_event_exists'] = True
                context['today_event_name'] = today_event.title
                context['today_event_id'] = today_event.id
            context['all_events_count'] = events.count()
            context['today_events_count'] = events.filter(date=date.date()).count()
            context['yesterday_events_count'] = events.filter(date=date.date() - timezone.timedelta(1)).count()
            last_events = events.filter(date__lte=date.date())
            context['week_events_count'] = last_events.filter(date__gte=date.date() - timezone.timedelta(1)).count()
            context['month_events_count'] = last_events.filter(date__gte=date.date() - timezone.timedelta(30)).count()
            context['year_events_count'] = last_events.filter(date__gte=date.date() - timezone.timedelta(365)).count()
            context['all_notes_count'] = notes.count()
            todos_info = Todos.get_amounts(request.user)
            context['all_todo_count'] = todos_info[0]
            context['active_todo_count'] = todos_info[1]
            context['finished_todo_count'] = todos_info[2]
            nearest_events = events.filter(date__gte=date.date()).order_by('date')
            if nearest_events.count() > 0:
                while (nearest_events.first().date == date.date()) and (nearest_events.first().time < date.time()):
                    nearest_events.pop(0)
                    if nearest_events.count() == 0:
                        break
            if nearest_events.first():
                context['nearest_event_exists'] = True
                context['nearest_event_name'] = nearest_events.first().title
                context['nearest_event_place'] = nearest_events.first().place
                context['nearest_event_date'] = nearest_events.first().date.strftime("%d.%m.%Y ") + \
                    nearest_events.first().time.strftime("%H:%M")
            else:
                context['nearest_event_exists'] = False
            nearest_todo = todos.filter(deadline__gte=date.date()).order_by('deadline')
            if nearest_todo.count() > 0:
                while (nearest_todo.first().deadline.date() == date.date()) and\
                        (nearest_todo.first().deadline.time() < date.time()):
                    nearest_todo.pop(0)
                    if nearest_todo.count() == 0:
                        break
            if nearest_todo.first():
                context['nearest_todo_exists'] = True
                context['nearest_todo_name'] = nearest_todo.first().title
            else:
                context['nearest_todo_exists'] = False
            last_note = notes.order_by('-added_time').first()
            if last_note:
                context['last_note_exists'] = True
                context['last_note_title'] = last_note.title
                context['last_note_id'] = last_note.id
            else:
                context['last_note_exists'] = False
            context['add_event_form'] = AddEventForm()
            context['save_note_form'] = SaveNoteForm()
            context['edit_note_form'] = EditNoteForm()
            context['last_notes'] = get_last_notes(request.user, notes)
            context['last_notes_count'] = len(context['last_notes'])
            context['add_todo_form'] = SaveTodoForm()
            context['edit_todo_form'] = EditTodoForm()
            context['hours'] = date.hour
            return render(request, "main/home.html", context)
    else:
        return HttpResponseRedirect('/')


def get_last_notes(user, notes):
    """!
            @brief Function that get last three notes out all
    """
    all_notes = Notes.get_notes("date_up", user, notes)
    if all_notes.count() >= 3:
        first_three = all_notes[0:3]
    else:
        first_three = all_notes
    return first_three


def get_active_todos(user):
    all_todos = Todos.get_todos("date_up", user)
    active_todos = []
    last_active_todos = []
    for item in all_todos:
        if item.status == 'in progress':
            active_todos.append(item)
    if active_todos.count() > 2:
        last_active_todos = active_todos[0:3]
    else:
        last_active_todos = active_todos[0:active_todos.count()]
    return last_active_todos


def get_finished_todos(user):
    all_todos = Todos.get_todos("date_up", user)
    finished_todos = []
    last_finished_todos = []
    for item in all_todos:
        if item.status != 'in progress':
            finished_todos.append(item)
    if finished_todos.count() > 2:
        last_finished_todos = finished_todos[0:3]
    else:
        last_finished_todos = finished_todos[0:finished_todos.count()]
    return last_finished_todos


def send_mail(mail):
    """!
            @brief Function that sends emails
    """
    subject = mail['subject']
    text_content = mail['text_content']
    from_email = mail['from_email']
    to_email = mail['to_email']
    html_content = mail['html_content']
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def sign_up_ajax(request):
    """!
            @brief Function that signs user up (with ajax)
    """
    if request.method == "GET":
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/')
    else:
        response_data = {}
        if not request.user.is_authenticated:
            form = SignUpForm(request.POST)
            language_checker = False
            timezone_checker = False
            if form.is_valid():
                language = form.cleaned_data['language']
                language_checker = language in SUPPORTED_LANGUAGES_CODES
                timezone_name = form.cleaned_data['timezone']
                timezone_checker = timezone_name in SUPPORTED_TIMEZONES
            if form.is_valid() and language_checker and timezone_checker:
                email = form.cleaned_data['email'].lower()
                username = form.cleaned_data['username'].lower()
                name = form.cleaned_data['name']
                surname = form.cleaned_data['surname']
                pass1 = form.cleaned_data['password1']
                pass2 = form.cleaned_data['password2']
                email_uniq = check_email_uniq(email)
                username_uniq = check_username_uniq(username)
                if email_uniq:
                    if username_uniq:
                        if pass1 == pass2:
                            user = User(email=email, username=username, first_name=name, last_name=surname, is_active=0)
                            user.set_password(pass1)
                            user.save()
                            lang = Language(user=user, lang=language)
                            lang.save()
                            timezone = Timezone(user=user, timezone=timezone_name)
                            timezone.save()
                            sign_up_key = create_unic_key(user, username, pass1)
                            sign_up_key.save()
                            mail = create_mail(user,
                                               "Go to this link to activate your account: eva-organizer.tk/activate/" +
                                               sign_up_key.key,
                                               "<a href='https://eva-organizer.tk/activate/" + sign_up_key.key +
                                               "'>Go to this link to activate your account</a>")
                            send_mail(mail)
                            result = "100"
                        else:
                            result = "101"
                    else:
                        result = "102"
                else:
                    result = "103"
            else:
                result = "104"
        else:
            result = "105"
        response_data['result'] = result
        return HttpResponse(json.dumps(response_data), content_type="application/json")

templates/main/about.html
<!DOCTYPE html>
<html>
<head>
    <title>About Eva</title>
</head>
<style>
    body {
        text-align: center;
        color: #fff;
        background-color: #000;
        margin-right: 5em;
        margin-left: 5em;
    }
    p {
        background-color: #333;
        border: 2px solid red;
        box-shadow: 0px 10px 10px 0px #000;
        padding: 25px;
    }
</style>
<body>
    <h1>About Eva</h1>
    <p> Ева, это сайт-органайзер. Ева - это ваш помощник по жизни. На нашем сайте присутствует 3 раздела : Заметки, Календарь, Напомнинания.
    Если вы придумали гениальную идею ,но вы боитесь ее забыть , Ева и ее раздел Заметки ,поможет вам.
    С Евой ,вы сможете отметить мероприятие  в нашем разделе Календарь

    Наш сайт оснащен синтезом речи от Яндекс. С помощью его мы наделили Еву голосом.
    С Евой ,и ее голосовыми напомниниями ,пользователь никогда не забудет о своих важных делах

    Каждую заметку, каждое напоминание
    пользователю не обязательно печатать, вы можете обратиться к Еве,и оставить голосовую заметку или напоминание
    В любую минуту вы сможете сменить язык с русского на английский ,в наших настройках сайта

    В нашем проекте минимум недочетов, и надеемся без багов.

    Над Евой работали ,самые ответственные Бэкэндеры и Фронтэндеры всего мира (51 первой группы)

    Команда фронтэндеров трудилась над созданием удобного и приятного дизайна. Цвет и основной стиль сайта ,не будет раздражать ваши глаза.

    Команда бэкэндеров ,грамотно написав движок сайта , смогла наделить наш проект жизнью </p>
</body>
</html>

templates/main/index_fixed_lang.html
<!DOCTYPE html>
<html lang="ru"><head>
    <title>Index page</title>
    
    <script src="https://webasr.yandex.net/jsapi/v1/webspeechkit.js" type="text/javascript"></script><script type="text/javascript" src="https://webasr.yandex.net/jsapi/v1/webspeechkit-settings.js?seed=0.08897884981706738"></script>
    <script src="/static/js/speechkit.js"></script>
    <script src="/static/js/jquery-3.2.1.slim.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/holder.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta charset="utf-8">
    


<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/general.css">
<link rel="stylesheet" href="/static/css/cover.css">
<script charset="utf-8" type="text/javascript" src="/static/js/setup_ajax.js"></script>
<script charset="utf-8" type="text/javascript" src="/static/js/main/index/scripts.js"></script>

</head>
<body>

<header>
    
</header>



<div class="text-center">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h1 class="masthead-brand">EVA</h1>
            </div>
        </header>
        <main>
            <section id="myCarousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Заметки</h1>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi
                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id
                                    elit.</p>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Календарь</h1>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi
                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id
                                    elit.</p>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item active">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Напоминания</h1>
                                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi
                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id
                                    elit.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            </section>
            <section id="login" class="login">
                <h2 class="cover-heading">Добро пожаловать</h2>
                <p class="lead">
                </p><form id="sign_up_form">
                    <input type="hidden" name="csrfmiddlewaretoken" value="ERFLNeURz9FMJu5mjsFyjJ1ltkImjLqCIJPUQkgPVSs2FLYFDSaMQEstGsnTS29r">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_username">Имя пользователя</label>
        

        <div class=" ">
            <input type="text" name="username" class="form-control form-control" maxlength="200" id="id_username" placeholder="Введите имя пользователя" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_email">Электронная почта</label>
        

        <div class=" ">
            <input type="text" name="email" class="form-control form-control" maxlength="200" id="id_email" placeholder="Введите адрес электронной почты" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_name">Имя</label>
        

        <div class=" ">
            <input type="text" name="name" class="form-control form-control" maxlength="200" id="id_name" placeholder="Введите ваше имя" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_surname">Фамимля</label>
        

        <div class=" ">
            <input type="text" name="surname" class="form-control form-control" maxlength="200" id="id_surname" placeholder="Введите вашу фамимлю" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_password1">Пароль</label>
        

        <div class=" ">
            <input type="password" name="password1" class="form-control form-control" maxlength="200" id="id_password1" placeholder="Введите пароль" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_password2">Пароль еще раз</label>
        

        <div class=" ">
            <input type="password" name="password2" class="form-control form-control" maxlength="200" id="id_password2" placeholder="Введите пароль еще раз" required="">

            

            
        </div>
    
</div>

                        </div>
                    </div>
                    <div class="form-check" style="margin-bottom: 20px;">
                        <input type="checkbox" class="form-check-input">
                        <label class="form-check-label">Я принимаю условия Пользовательского соглашения и Политики
                            конфиденциальности</label>
                    </div>
                    <a class="btn btn-success btn-block" id="sign_up_btn" onclick="sign_up_ajax()">Зарегистрироваться</a>
                </form>
                <p class="lead" style="margin-top: 50px;">
                </p><h3 class="cover-heading">Уже с нами?</h3>
                <form id="sign_in_form">
                    <input type="hidden" name="csrfmiddlewaretoken" value="ERFLNeURz9FMJu5mjsFyjJ1ltkImjLqCIJPUQkgPVSs2FLYFDSaMQEstGsnTS29r">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_username">Имя пользователя или эл. почта</label>
        

        <div class=" ">
            <input type="text" name="username" class="form-control form-control" maxlength="200" id="id_username" placeholder="Введите имя пользователя или эл. почту" required="">

            

            
        </div>
    
</div>

                        </div>
                        <div class="form-group col-md-6">
                            

<div class="form-group">
    
        
            <label class="control-label  " for="id_password">Пароль</label>
        

        <div class=" ">
            <input type="password" name="password" class="form-control form-control" maxlength="200" id="id_password" placeholder="Введите пароль" required="">

            

            
        </div>
    
</div>

                        </div>
                    </div>
                    <a class="btn btn-primary btn-block" id="sign_in_btn" onclick="sign_in_ajax()">Войти</a>
                </form>
            </section>
        </main>
        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>MPS51 Team</p>
            </div>
        </footer>
    </div>
</div>






<script>init_speechkit();</script>




</body></html>

templates/main/profile.html
{% extends "main/base.html" %}

{% block meta %}
    {% load staticfiles %}
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/general.css" %}'>
	<link rel="stylesheet" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" href='{% static "css/profile.css" %}'>
    <script charset='utf-8' type="text/javascript" src='{% static "js/setup_ajax.js" %}'></script>
	<script charset='utf-8' type="text/javascript" src='{% static "js/main/profile/scripts.js" %}'></script>
{% endblock %}

{% block content %}
	<section class="profile">
		<div class="card text-center">
			<div class="card-header">
				<h1> Личный кабинет </h1>
			</div>
			<div class="card-body">
				<picture>
					<img src='{% static "/img/avatar_user.png" %}' class="avatar">
				</picture>
				<div class="data">
					<span>Ник</span>
					<h2 class="card-title" id="username">{{ user.username }}</h2>
				</div>
				<div class="data" style="margin-top: 25px;">
					<span>Имя</span>
					<h2 class="card-title" id="name">{{ user.first_name }}</h2>
				</div>
				<div class="data">
					<span>Фамилия</span>
					<h2 class="card-title" id="surname">{{ user.last_name }}</h2>
				</div>
				<div class="data">
					<span>Email</span>
					<h2 class="card-title" id="email">{{ user.email }}</h2>
				</div>
			</div>
			<div class="card-footer">
				<button type="button" class="btn btn-lg btn-light" onclick="get_user_data()" data-toggle="modal" data-target="#Edit">
					<picture><img src='{% static "/icons/edit_icon.png" %}' class="icon"></picture>
				</button>
				<button type="button" class="btn btn-lg btn-light" data-toggle="modal" data-target="#Settings">
					<picture><img src='{% static "/icons/settings_icon.png" %}' class="icon"></picture>
				</button>
			</div>
		</div>
	</section>
	<section>
		<div class="modal fade" id="Edit">
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h2 class="modal-title">Редактировать профиль {{user.username}}</h2>
					</div>
					<div class="modal-body">
						<div class="form-group btn btn-light change-avatar">
							<label>Изменить аватар</label>
							<input type="file" class="form-control-file">
						</div>
						<form id="change_user_data_form">
							<div class="form-row">
								<div class="form-group col-md-6">
									<label for="inputEmail4">Имя</label>
									{{ change_user_data_form.name }}
								</div>
								<div class="form-group col-md-6">
									<label for="inputPassword4">Фамилия</label>
									{{ change_user_data_form.surname }}
								</div>
							</div>
							<hr>
							<div class="form-group">
								<label for="inputEmail4">Email</label>
								{{ change_user_data_form.email }}
							</div>
						</form>
						<hr>
						<form id="change_password_form">
							<div class="form-group">
								<label for="inputPassword4">Старый пароль</label>
								{{ change_password_form.old_password }}
							</div>
							<div class="form-group">
								<label for="inputPassword4"> Новый пароль</label>
								{{ change_password_form.new_password1 }}
							</div>
							<div class="form-group">
								<label for="inputPassword4">Повторить новый пароль</label>
								{{ change_password_form.new_password2 }}
							</div>
						</form>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-light" data-dismiss="modal">Отменить</button>
						<button type="submit" class="btn btn-light" id="save_changes_btn" onclick="change_user_data(); get_user_data();">Сохранить</button>
						<button type="submit" class="btn btn-light" id="change_password_btn" onclick="change_password()">Изменить пароль</button>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fade" id="Settings">
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h2 class="modal-title">Настройки</h2>
					</div>
					<div class="modal-body">
						<span>Выберите язык:</span>
						<div class="btn-group btn-group-lg" style="margin-left: 185px;">
							<button type="button"  onclick="$('#id_language').val('ru')" class="btn btn-light active">Русский</button>
							<button type="button" onclick="$('#id_language').val('en')" class="btn btn-light">Английский</button>
							<button type="button" class="btn btn-light" disabled>Немецкий</button>
						</div>
						<form id="change_language_form" hidden>
							{{ change_language_form }}
						</form>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-light" data-dismiss="modal">Отменить</button>
						<button type="submit" onclick="change_language_ajax()" id="change_language_btn" class="btn btn-light">Сохранить</button>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}